version: '3.5'

services:
  server:
    image: alpine:latest
    entrypoint: /app/server/entrypoint.sh
    command: "/app/server/pocketbase serve --dev --http 0.0.0.0:8090 --publicDir ../web/build"
    user: ${UID}:${GID}
    expose:
      - 8090
    working_dir: /app/server
    environment:
      - HOME=/app/server
      - AUDITLOG=${AUDITLOG}
    volumes:
      - ${PWD}/server:/app/server
      - ${PWD}/web:/app/web
      - ${HOME}/go/pkg:/go/pkg
  web:
    image: node:22-alpine
    user: ${UID}:${GID}
    # sveltekit build
    command: sh -c "npx pnpm install && npm run build"
    volumes:
      - ${PWD}/web:/app/web
      - ${PWD}/server:/app/server
    environment:
      - HOME=/app/web
    working_dir: /app/web
